// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SF.Tecnologias.Infrastructure.Persistence;

#nullable disable

namespace SF.Tecnologias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921000000_SQLiteInitialCreate")]
    partial class SQLiteInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SF.Tecnologias.Domain.Empresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CriadoEm")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("AtualizadoEm")
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Codigo")
                    .IsUnique();

                b.HasIndex("Nome");

                b.ToTable("Empresas");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CriadoEm")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("AtualizadoEm")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("SenhaHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Perfil", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Nome")
                    .IsUnique();

                b.ToTable("Perfis");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Permissao", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int?>("PerfilId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Nome")
                    .IsUnique();

                b.HasIndex("PerfilId");

                b.ToTable("Permissoes");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.UsuarioEmpresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<int>("PerfilId")
                    .HasColumnType("INTEGER");

                b.Property<int>("UsuarioId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("EmpresaId");

                b.HasIndex("PerfilId");

                b.HasIndex(new[] { "UsuarioId", "EmpresaId" }, "IX_UsuarioEmpresas_UsuarioId_EmpresaId")
                    .IsUnique();

                b.ToTable("UsuarioEmpresas");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Categoria", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Ordem")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.HasKey("Id");

                b.HasIndex(new[] { "EmpresaId", "Nome" }, "IX_Categorias_EmpresaId_Nome")
                    .IsUnique();

                b.ToTable("Categorias");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<string>("Cpf")
                    .HasMaxLength(14)
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Endereco")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Observacoes")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Telefone")
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex(new[] { "EmpresaId", "Nome" }, "IX_Clientes_EmpresaId_Nome");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Mesa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<int>("Capacidade")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(4);

                b.Property<string>("Descricao")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Numero")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex(new[] { "EmpresaId", "Numero" }, "IX_Mesas_EmpresaId_Numero")
                    .IsUnique();

                b.ToTable("Mesas");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Produto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<int?>("CategoriaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<decimal?>("PrecoCusto")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("PrecoVenda")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("CategoriaId");

                b.HasIndex(new[] { "EmpresaId", "Codigo" }, "IX_Produtos_EmpresaId_Codigo")
                    .IsUnique();

                b.HasIndex(new[] { "EmpresaId", "Nome" }, "IX_Produtos_EmpresaId_Nome");

                b.ToTable("Produtos");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.SessaoCaixa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("EmpresaId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MesaId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("UsuarioId")
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("ValorFechamento")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("ValorInicial")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex(new[] { "EmpresaId", "Status" }, "IX_SessoesCaixa_EmpresaId_Status");

                b.HasIndex("MesaId");

                b.HasIndex("UsuarioId");

                b.ToTable("SessoesCaixa");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Permissao", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Perfil", null)
                    .WithMany("Permissoes")
                    .HasForeignKey("PerfilId");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.UsuarioEmpresa", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany("UsuarioEmpresas")
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SF.Tecnologias.Domain.Perfil", "Perfil")
                    .WithMany("UsuarioEmpresas")
                    .HasForeignKey("PerfilId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SF.Tecnologias.Domain.Usuario", "Usuario")
                    .WithMany("UsuarioEmpresas")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");

                b.Navigation("Perfil");

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Categoria", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Cliente", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Mesa", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Produto", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Categoria", "Categoria")
                    .WithMany()
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Categoria");

                b.Navigation("Empresa");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.SessaoCaixa", b =>
            {
                b.HasOne("SF.Tecnologias.Domain.Empresa", "Empresa")
                    .WithMany()
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SF.Tecnologias.Domain.Mesa", "Mesa")
                    .WithMany()
                    .HasForeignKey("MesaId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("SF.Tecnologias.Domain.Usuario", "Usuario")
                    .WithMany()
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Empresa");

                b.Navigation("Mesa");

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Empresa", b =>
            {
                b.Navigation("UsuarioEmpresas");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Usuario", b =>
            {
                b.Navigation("UsuarioEmpresas");
            });

            modelBuilder.Entity("SF.Tecnologias.Domain.Perfil", b =>
            {
                b.Navigation("Permissoes");

                b.Navigation("UsuarioEmpresas");
            });
#pragma warning restore 612, 618
        }
    }
}
